"""Documentation generation (Markdown).

Wikdoc can generate Markdown documentation for a workspace.

Templates:
  - wiki: creates a small wiki structure
  - readme: generates a README skeleton
  - architecture: generates an Architecture.md skeleton
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Optional

from ..config import Workspace, RuntimeOptions
from ..vectordb.base import VectorStore
from ..rag.answer import LLMClient


def _safe_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _tree_overview(root: Path, max_depth: int = 3, max_entries: int = 400) -> str:
    lines: List[str] = []
    root = root.resolve()
    count = 0

    def walk(d: Path, depth: int) -> None:
        nonlocal count
        if depth > max_depth or count > max_entries:
            return
        entries = sorted([p for p in d.iterdir() if not p.name.startswith(".")], key=lambda p: (p.is_file(), p.name))
        for p in entries:
            if count > max_entries:
                return
            prefix = "  " * depth + ("- " if depth > 0 else "")
            if p.is_dir():
                lines.append(f"{prefix}{p.name}/")
                count += 1
                walk(p, depth + 1)
            else:
                lines.append(f"{prefix}{p.name}")
                count += 1

    lines.append(str(root))
    walk(root, 1)
    if count > max_entries:
        lines.append("... (truncated)")
    return "\n".join(lines)


def generate_docs(
    workspace: Workspace,
    store: VectorStore,
    out_dir: Path,
    template: str = "wiki",
    llm: Optional[LLMClient] = None,
    runtime: Optional[RuntimeOptions] = None,
) -> List[Path]:
    runtime = runtime or RuntimeOptions()
    written: List[Path] = []

    tree = _tree_overview(workspace.root)
    stats = store.stats()

    if template == "readme":
        content = (
            f"# {workspace.name or workspace.root.name}\n\n"
            f"> Generated by Wikdoc.\n\n"
            "## Overview\n\n"
            "(Add a short description of the project.)\n\n"
            "## Structure\n\n"
            "```text\n" + tree + "\n```\n\n"
            "## Quickstart\n\n"
            "- Add commands to run/build/test.\n\n"
            "## Index stats\n\n"
            f"- Indexed chunks: {stats.get('chunks')}\n"
        )
        p = out_dir / "README.generated.md"
        _safe_write(p, content)
        written.append(p)
        return written

    if template == "architecture":
        content = (
            "# Architecture\n\n"
            "> Generated by Wikdoc. Validate and edit before publishing.\n\n"
            "## High-level\n\n"
            "- Components:\n"
            "- Data flow:\n"
            "- External integrations:\n\n"
            "## Folder map\n\n"
            "```text\n" + tree + "\n```\n\n"
            "## Key design decisions\n\n"
            "- (Add ADR links here.)\n"
        )
        p = out_dir / "Architecture.generated.md"
        _safe_write(p, content)
        written.append(p)
        return written

    home = (
        f"# {workspace.name or workspace.root.name} Wiki\n\n"
        "> Generated by Wikdoc.\n\n"
        "## Workspace\n\n"
        f"- Path: `{workspace.root}`\n"
        f"- Indexed chunks: **{stats.get('chunks')}**\n\n"
        "## Folder overview\n\n"
        "```text\n" + tree + "\n```\n\n"
        "## Pages\n\n"
        "- [Architecture](architecture.md)\n"
        "- [Glossary](glossary.md)\n"
    )
    p_index = out_dir / "index.md"
    _safe_write(p_index, home)
    written.append(p_index)

    arch = (
        "# Architecture\n\n"
        "> Generated by Wikdoc.\n\n"
        "## Summary\n\n"
        "(Future: enrich with LLM + citations.)\n\n"
        "## Components\n\n"
        "- ...\n\n"
        "## Data flow\n\n"
        "- ...\n\n"
        "## Entry points\n\n"
        "- ...\n"
    )
    p_arch = out_dir / "architecture.md"
    _safe_write(p_arch, arch)
    written.append(p_arch)

    glossary = (
        "# Glossary\n\n"
        "> Add domain terms, acronyms and their meaning.\n\n"
        "- Term: Definition\n"
    )
    p_gloss = out_dir / "glossary.md"
    _safe_write(p_gloss, glossary)
    written.append(p_gloss)

    return written
